# Generated by Django 3.0.6 on 2020-05-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imagefile', models.FileField(null=True, upload_to='images/', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='rent1payee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_email', models.EmailField(max_length=254)),
                ('p_name', models.CharField(max_length=100)),
                ('p_country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rentyourhouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('From', models.CharField(max_length=100)),
                ('To', models.CharField(max_length=100)),
                ('adults', models.CharField(max_length=100)),
                ('children', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=100)),
                ('appointment', models.TimeField()),
                ('roomdescription', models.CharField(max_length=500)),
                ('tenantdescription', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
