# Generated by Django 3.0.6 on 2020-05-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentyourhouse',
            name='citylocation',
            field=models.CharField(default='location not clear', max_length=100),
        ),
        migrations.AddField(
            model_name='rentyourhouse',
            name='houselocation',
            field=models.CharField(default='location not clear', max_length=100),
        ),
        migrations.AddField(
            model_name='rentyourhouse',
            name='localitylocation',
            field=models.CharField(default='location not clear', max_length=100),
        ),
    ]
