# Generated by Django 3.0.6 on 2020-05-18 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_auto_20200518_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='rent_your_house',
            field=models.ForeignKey(null=2, on_delete=django.db.models.deletion.CASCADE, related_name='img', to='first.Rentyourhouse'),
            preserve_default=2,
        ),
    ]
